---
title: 'Class 6: R functions'
author: "Brie Diaz"
date: "4/19/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
Today we will focus on **R functions** but we will start with a bit of **file reading

```{r}
plot(1:10, type="l", col="blue")
```
```{r}
read.csv("test1.txt", header = TRUE)
```

```{r}
read.delim("test2.txt", header = TRUE, sep = "$")
```

```{r}
read.table("test3.txt", sep = "")
```


```{r}
read.csv("https://bioboot.github.io/bggn213_S19/class-material/test1.txt")
```

## Our first function

Add some numbers 

```{r}
add <- function(x, y=1) {
  # The body
  x+y
}
```


```{r}
add(4)
```


```{r}
add(c(1,3,5), 1)
```

```{r}
add(c(1,3,5))
```




```{r}
#add( 1, 3, 5)

```


```{r}
#add(x=1, y="barry")
```



```{r}
## You need a “name”, “arguments” and “body”…
rescale <- function(x) {
rng <-range(x)
(x - rng[1]) / (rng[2] - rng[1])
}
# Test on a small example where you know the answer
rescale(1:10)
```

```{r}
rescale( c(1, 3, NA, 5, 10))
```


```{r}
x <- c(1, 3, NA, 5, 10)

rng <-range(x, na.rm = TRUE)
rng
(x - rng[1]) / (rng[2] - rng[1])

```


```{r}
rescale2 <- function(x, na.rm = TRUE) {
rng <-range(x, na.rm = na.rm)
(x - rng[1]) / (rng[2] - rng[1])
}
```


```{r}
rescale2(c(1, 3, NA, 10))
```



```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
if(na.rm) {
rng <-range(x, na.rm=TRUE)
} else {
rng <-range(x)
}
print("Hello")
answer <- (x - rng[1]) / (rng[2] - rng[1])
print("is it me you are looking for?")
if(plot) {
plot(answer, typ="b", lwd=4)
}
print("I can see it in ...")
return(answer)
}

```


```{r}
rescale3(1:10)
```

```{r}
rescale3(1:10, plot = TRUE)
```



















